<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Clientes.aspx.cs" Inherits="M17_Modelo_T1.Clientes" ValidateRequest="false" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <script src="js/jquery-1.11.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/clientesform.js"></script>
</head>
<body>
    <div class="container">
    <form id="form1" runat="server" >
        <div class="form-group">
            <label for="tbNome">Nome</label><asp:TextBox ID="tbNome" runat="server" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label for="tbMorada">Morada</label><asp:TextBox ID="tbMorada" runat="server" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label for="tbCP">Código Postal</label><asp:TextBox ID="tbCP" runat="server" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label for="tbDataNascimento">Data Nascimento</label><asp:TextBox ID="tbDataNascimento" runat="server" CssClass="form-control" TextMode="Date" ></asp:TextBox>
        </div>
        <div class="form-group">
            <label for="tbEmail">Email</label><asp:TextBox ID="tbEmail" runat="server" CssClass="form-control" TextMode="Email"></asp:TextBox>
        </div>
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Adicionar" CssClass="btn btn-info" />
        <br />
        <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
        <h1>Lista de clientes</h1>
        <asp:GridView ID="GridView1" runat="server" CssClass="table" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowCreated="GridView1_RowCreated" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating"></asp:GridView>
    </form>
    </div>
</body>
</html>
