<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Clientes.aspx.cs" Inherits="M17_Modelo_T1.Clientes" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <script src="js/jquery-1.11.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
    <form id="form1" runat="server">
        
        Nome:<asp:TextBox ID="tbNome" runat="server"></asp:TextBox>
        <br />
        Morada:<asp:TextBox ID="tbMorada" runat="server"></asp:TextBox>
        <br />
        Código Postal:<asp:TextBox ID="tbCP" runat="server"></asp:TextBox>
        <br />
        Data Nascimento:<asp:TextBox ID="tbDataNascimento" runat="server"></asp:TextBox>
        <br />
        Email:<asp:TextBox ID="tbEmail" runat="server"></asp:TextBox>
        <br />
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Adicionar" CssClass="btn btn-info" />
        <br />
        <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
        <h1>Lista de clientes</h1>
        <asp:GridView ID="GridView1" runat="server" CssClass="table" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowCreated="GridView1_RowCreated" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating"></asp:GridView>
    </form>
    </div>
</body>
</html>
